mysiteS20/myapp/urls.py
from django.urls import path, re_path
from myapp import views

app_name = 'myapp'

urlpatterns = [

    path(r'', views.index, name='index'),
    path(r'about/', views.about, name='about'),
    path(r'<int:top_no>', views.detail, name='top_no'),
    path(r'courses/', views.courses, name='courses'),
    path(r'place_order/', views.place_order, name='place_order'),
    path(r'courses/<int:cour_id>', views.coursedetail, name='coursedetail'),
    path(r'login/', views.user_login, name='user_login'),
    path(r'logout/', views.user_logout, name='user_logout'),
    path(r'myaccount/<int:st_id>', views.myaccount, name='myaccount'),
    path(r'register/', views.register, name='register'),



]

mysiteS20/mysiteS20/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.conf.urls import include, url

app_name = 'myapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),

    path('', include('django.contrib.auth.urls')),
    #url(r'^', include('django.contrib.auth.urls')),
    url(r'', include('django.contrib.auth.urls')),

    url(r"^accounts/", include("django.contrib.auth.urls")),
    url('password_reset/', auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html"),
        name='password_reset'),
    url(r'reset_password/done/', auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html")),
    url(r'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),
        name='password_reset_confirm'),
    url('password_reset_complete/',
        auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),
        name='password_reset_complete'),
    path('signin/', auth_views.LoginView.as_view(), name='signin'),

]

mysiteS20/myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

def validate_range(value):
    if value < 100 or value > 200:
        raise ValidationError(
            _('%(value)s is not in range of 100 to 200'),
            params={'value': value},
        )

# Create your models here.
class Topic(models.Model):
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=200, blank=True)
    def __str__(self):
        return self.name

class Course(models.Model):
    topic = models.ForeignKey(Topic, related_name='courses', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[validate_range])
    for_everyone = models.BooleanField(default=True)
    description = models.TextField(max_length=300, null=True, blank=True)
    #Lab7 Fields Added
    interested = models.PositiveIntegerField(default=0)
    stages = models.PositiveIntegerField(default=3)
    #Final Project
    hours = models.IntegerField(default=1)
    def __str__(self):
        return self.name

    def __float__(self):
        return self.price

    def discount(self):
        return (float(self.price) * 0.9)

class Student(User):
    CITY_CHOICES = [('WS', 'Windsor'),
        ('CG', 'Calgery'),
        ('MR', 'Montreal'),
        ('VC', 'Vancouver')]
    school = models.CharField(max_length=50, null=True, blank=True)
    city = models.CharField(max_length=2, choices=CITY_CHOICES, default='WS')
    interested_in = models.ManyToManyField(Topic)
    def __str__(self):
        return self.first_name + " " + self.last_name

class Order(models.Model):
    ORDER_STATUS_CHOICES = [(0, 'Cancelled'), (1, 'Order Confirmed')]
    course = models.ForeignKey(Course, related_name='course', on_delete=models.CASCADE)
    Student = models.ForeignKey(Student, related_name='Student', on_delete=models.CASCADE, max_length=200)
    levels = models.PositiveIntegerField()
    order_status = models.IntegerField(choices=ORDER_STATUS_CHOICES, default=1)
    order_date = models.DateField(default=datetime.date.today)

    def total_cost(self):
        total = 0
        for item in self.course.all():
            if Course.__str__(item):
                total += Course.__float__(item)
        return str(total)

    def __str__(self):
        return str(self.course)


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    def __str__(self):
        return self.user.username

mysiteS20/myapp/forms.py
from django import forms
from myapp.models import Order, Student, UserProfileInfo
from django.contrib.auth.models import User

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['Student', 'course', 'levels', 'order_date']
        #widgets = {
        #    'Student': forms.RadioSelect(),
        #    'order_date': forms.SelectDateWidget(),
        #}
        student = forms.RadioSelect()
        order_date = forms.DateField(widget=forms.SelectDateWidget)


class InterestForm(forms.Form):
    interested = forms.ChoiceField(
        choices=[('1', 'Yes'), ('0', 'No')],
        widget=forms.RadioSelect)
    levels = forms.IntegerField(min_value=1, initial=1)
    comments = forms.CharField(widget=forms.Textarea, required=False, label="Additional Comments")

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password', 'first_name', 'last_name')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = Student
        fields = ('city', 'interested_in')
        model = UserProfileInfo
        fields = ('profile_pic',)

mysiteS20/myapp/views.py
import sys
from django.shortcuts import render, redirect, reverse
# Import necessary classes
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, Http404

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from . import forms
from .forms import OrderForm, InterestForm, UserForm, UserProfileInfoForm
from .models import Topic, Course, Student, Order
from datetime import datetime

# Create your views here.

def courses(request):
    courlist = Course.objects.all().order_by('id')
    return render(request, 'myapp/courses.html', {'courlist': courlist})

def index(request):
    top_list = Topic.objects.all().order_by('id')[:10]

    #For Last Login
    if request.COOKIES.get('last_login'):
        login_time = request.COOKIES.get('last_login')
    else:
        login_time = 'Your last login was more than one hour ago'
    response = HttpResponse(render(request, 'myapp/index.html', {'top_list': top_list, 'login_time': login_time}))
    response.set_cookie('last_login', login_time, max_age=5)
    response.delete_cookie('last_login', login_time)

    #For Visit Counter
    about_visits = int(request.COOKIES.get('about_visits', '0'))
    response.set_cookie('about_visits', about_visits + 1)
    return response
    #  Are you passing any extra context variables to the template? If so, what are you passing?
    # Answer: Yes we are passing Topic list by their order id so that in index.html we can list all the topics

def about(request):

    #if request.session.test_cookie_worked():
    #    print("The Test Cookies worked")
    #    request.session.delete_test_cookie()

    #For Visit Counter
    if request.COOKIES.get('about_visits'):
        mynum = request.COOKIES.get('about_visits')
    else:
        mynum = 0
    response = render(request, 'myapp/about.html', {'mynum' : mynum})
    response.set_cookie('about_visits', mynum, expires=5)
    response.delete_cookie('about_visits', mynum)
    return response
    #return render(request, 'myapp/about.html')
    # Do you need to pass any extra context variables to the template?
    # Answer: No we dont need to pass any extra variable for this as this page is only for display


def detail(request, top_no):
    top_list = Topic.objects.filter(id=top_no)
    c_list = Course.objects.all()
    get_object_or_404(top_list, id=top_no)
    return render(request, 'myapp/detail.html', {'top_list': top_list, 'c_list': c_list})
    # Do you need to pass any extra context variables to the template?
    # Answer: Yes, we are passing Course Object (as dictionary) along with topics list,
    # so that we can get all the courses listed in that topic


# place order view
def place_order(request):
    msg = ''
    courlist = Course.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.levels <= order.course.stages:
                if (order.course.price > 150.00):
                    Course.discount(order.course)
                order.save()
                msg = 'Your course has been ordered successfully.'
            else:
                msg = 'You exceeded the number of levels for this course.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'courlist': courlist})

def coursedetail(request, cour_id):
    cour = Course.objects.get(pk=cour_id)
    if request.method == 'POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            if form['interested'].value() == '1':
                Course.objects.filter(pk=cour_id).update(interested = cour.interested + 1)
        return redirect('myapp:index')
    else:
        form = InterestForm()
    return render(request, 'myapp/coursedetail.html', {'cour': cour, 'InterestForm': form})

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                # For Last Login
                response = HttpResponseRedirect(reverse('myapp:index'))
                print('Hello')
                if 'last_login' in request.COOKIES:
                    last_login = request.COOKIES['last_login']
                    # the cookie is a string - convert back to a datetime type
                    last_login_time = datetime.strptime(last_login[:-7], "%Y-%m-%d %H:%M:%S")
                    curr_time = datetime.now()
                    if (curr_time - last_login_time).days > 0:
                        response.set_cookie('last_login', datetime.now(),max_age=3600) # 1 hours Expiry
                    response = HttpResponseRedirect(reverse('myapp:myaccount/request.user.id'))
                else:
                    response.set_cookie('last_login', datetime.now(),max_age=3600) # 1 hours Expiry
                return response
                #return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')

@login_required
def user_logout(request):
    #logout(request)
    response = HttpResponseRedirect(reverse(('myapp:index')))
    response.delete_cookie('last_login')
    response.delete_cookie('sessionid')
    return response

def myaccount(request, st_id):
    if st_id != 0:
        try:
            if Student.objects.get(pk=st_id):
                if request.user.id == st_id:
                    user = get_object_or_404(Student, pk=st_id)
                    interested = Student.objects.filter(id=st_id).values_list('interested_in__courses__name',flat=True)
                    stud_course = Order.objects.filter(Student_id=st_id).values_list('course__name', flat=True)
                    return render(request,'myapp/myaccount.html', {'user': user, 'interested': interested, 'stud_course':stud_course})
                else:
                    msg = 'You are not a login user'
                    return render(request, 'myapp/order_response.html', {'msg': msg})
        except:
            msg = 'You are not a registered student'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        return render(request, 'myapp/login.html')



def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'myapp/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

mysiteS20/myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <h3>This is About Page</h3>
    <h3>Page visit: {{ mynum }}</h3>
{% endblock %}

mysiteS20/myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h3>This is About Page</h3>
    <p><a href="/myapp">Home Page</a></p>
</body>
</html>

mysiteS20/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link  rel="stylesheet"  type="text/css"  href="{%  static  'myapp/style.css' %}" />
        <title>E-Learning WebApp-{% block title %}Welcome!{% endblock %}</title>
    </head>
    <body>
        <div>
            <h1>{% block myhdg %}Hello {{request.user.first_name}} {{request.user.last_name}} {% endblock %}</h1>
            {% block body_block %}*** {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
                <li  class="hbar1"><a  href="/myapp/about/">Find  out  about our  E-Learning site</a></li>
                <li class="hbar1"><a href = "{% url 'myapp:index' %}">Click here to return to main page</a><br/></li>
                <li class="hbar1"><a href = "{% url 'myapp:courses' %}">List of Courses available</a><br/></li>
                {% if request.user.id %}
                    <li class="hbar1"><a href = "{% url 'myapp:myaccount' request.user.id|default:0 %}">My Account</a></li>
                    <li class="hbar1"><a href = "{% url 'myapp:user_logout' %}">Logout</a></li>
                {% else %}
                    <li class="hbar1"><a href = "{% url 'myapp:user_login' %}">Login</a></li>
                    <li class="hbar1"><a href = "{% url 'myapp:register' %}">Register Here</a></li>
                {% endif %}
            </ul>
        </div>
    </body>
</html>

mysiteS20/myapp/templates/myapp/coursedetail.html
{% extends 'myapp/base.html' %}

{% block body_block %}

    <p>
        Course Name: {{ cour.name }}<br>
        Price {{ cour.price }}<br>
        Interested Students {{ cour.interested }}<br>
        {% if cour.for_everyone is False %}
            <b>This course is not for everyone</b>
        {% endif %}
    </p>
    <h1>Interest Form</h1>
    <form method="POST">
        {% csrf_token %}
        {{ InterestForm }}
        <input type="submit" value="Save">
    </form>

{% endblock %}

mysiteS20/myapp/templates/myapp/courses.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if courlist %}
        <h2>List of Courses</h2>
        <ol>
            {% for cor in courlist %}
                <li><a href="/myapp/courses/{{ cor.id }}">{{ cor.name}}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available Courses!</strong>
    {% endif %}
    <p><a href="{% url 'myapp:place_order' %}">Place order</a></p>

{% endblock %}

mysiteS20/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if top_list %}
        <h2>This is Topic Page for:</h2>
        <ol>
            {% for top in top_list %}
                <h3>{{ top.name}}</h3>
                <h3>Category:</h3>
                <ol>{{top.category}}</ol>
                <h3>List of Courses:</h3>
                {% for cour in c_list %}
                    {% if cour.topic == top %}
                        <ol>{{ cour.name }}</ol>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}
{% endblock %}

mysiteS20/myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% if top_list %}
        <h2>This is Topic Page for:</h2>
        <ol>
            {% for top in top_list %}
                <h3>{{ top.name}}</h3>
                <h3>Category:</h3>
                <ol>{{top.category}}</ol>
                <h3>List of Courses:</h3>
                {% for cour in c_list %}
                    {% if cour.topic == top %}
                        <ol>{{ cour.name }}</ol>
                    {% endif %}
                {% endfor %}
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}
    <p><a href="/myapp">Home Page</a></p>
</body>
</html>

mysiteS20/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if top_list %}
        <h2>List of Topics</h2>
        <ol>
            {% for top in top_list %}
                <li><a href="/myapp/{{ top.id }}">{{ top.name}}</a></li>
            {% endfor %}
        </ol>
        <h3>Login Time: {{ login_time }}</h3>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}


{% endblock %}

mysiteS20/myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>E-Learning WebApp!</title>
</head>
<body>
    {% if top_list %}
        <h2>List of Topics</h2>
        <ol>
            {% for top in top_list %}
                <li><a href="/myapp/{{ top.id }}">{{ top.name}}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <strong>There are no available topics!</strong>
    {% endif %}
    <p><a href="/myapp/about">About page</a></p>
</body>
</html>

mysiteS20/myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="{% url 'myapp:user_login' %}" method="post">
    {% csrf_token %}
        {{ form.as_p }}
    <div class="form-group">
        <b><label for="username">Username:</label></b>
        <input type="input" name="username" class="form-control" required>
    </div>
    <div>
        <b><label for="password">Password:</label></b>
        <input type="password" name="password" class="form-control" required>
    </div>
    <br>
    <input type="submit" name="submit" value="Login" class="btn btn-primary"/>
    <a href="password_reset/">Reset Password</a>


    </form>
{% endblock %}

mysiteS20/myapp/templates/myapp/myaccount.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <p>
        First Name: {{ user.first_name }}<br>
        Last Name: {{ user.last_name }}<br>
        <h3>Interested In:</h3>
        {% for inter in interested %}
            {{ inter }}<br>
        {% endfor %}
        <h3>Order List:</h3>
        {% for stud in stud_course %}
            {{ stud }}<br>
        {% endfor %}
    </p>
{% endblock %}

mysiteS20/myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if msg %}
        <strong>{{ msg }}</strong>
    {% else %}
        <strong>Order not placed, Try again</strong>
    {% endif %}
{% endblock %}

mysiteS20/myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {%  for course in courlist %}
        {{ course }}<br>
    {% endfor %}

    <form method="POST" >
    {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Save"/>
    </form>
{% endblock %}

mysiteS20/myapp/templates/myapp/registration.html
{% extends "myapp/base.html" %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}